title: BigBacter Docs
description: Documentation for the BigBacter pipeline
theme: just-the-docs

url: https://github.com/waphl-bioinformatics/bigbacter-docs

baseurl: "/bigbacter-docs"

favicon_ico: "/assets/media/bigbacter_logo.ico"

aux_links:
  BigBacter GitHub: https://github.com/DOH-JDJ0303/bigbacter-nf

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: red
  example:
    title: Example
    color: yellow